import { z } from "zod";

const addr = z.string().regex(/^0x[a-fA-F0-9]{40}$/, "Invalid EVM address");
const num = z.coerce.number();

export const clientEnv = z.object({
  NEXT_PUBLIC_USDC_ADDRESS: addr,
  NEXT_PUBLIC_ESCROW_ADDRESS: addr,
  NEXT_PUBLIC_USDC_DECIMALS: num,
  NEXT_PUBLIC_BASE_CHAIN_ID: num,
  NEXT_PUBLIC_PLATFORM_FEE_BPS: num,
}).parse({
  NEXT_PUBLIC_USDC_ADDRESS: process.env.NEXT_PUBLIC_USDC_ADDRESS,
  NEXT_PUBLIC_ESCROW_ADDRESS: process.env.NEXT_PUBLIC_ESCROW_ADDRESS,
  NEXT_PUBLIC_USDC_DECIMALS: process.env.NEXT_PUBLIC_USDC_DECIMALS,
  NEXT_PUBLIC_BASE_CHAIN_ID: process.env.NEXT_PUBLIC_BASE_CHAIN_ID,
  NEXT_PUBLIC_PLATFORM_FEE_BPS: process.env.NEXT_PUBLIC_PLATFORM_FEE_BPS,
});

export const {
  NEXT_PUBLIC_USDC_ADDRESS,
  NEXT_PUBLIC_ESCROW_ADDRESS,
  NEXT_PUBLIC_USDC_DECIMALS,
  NEXT_PUBLIC_BASE_CHAIN_ID,
  NEXT_PUBLIC_PLATFORM_FEE_BPS,
} = clientEnv;
